version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app_frontend
    volumes:
      - /app/node_modules #개발환경에서 코드 수정시 node_modules은 호스트의 node_modules를 참조하지 않음.
      - ./frontend:/app
    stdin_open: true #react app 종료시 발생하는 버그를 잡아줌

  # proxy nginx
  nginx:
    restart: always #재시작 정책
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app_backend
    volumes:
      - /app/node_modules #개발환경에서 코드 수정시 node_modules은 호스트의 node_modules를 참조하지 않음.
      - ./backend:/app
    environment:
      MYSQL_HOST: app_mysql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: xorudA0805!
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3306
