name: Deploy Fullstack app to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image for Tests
        run: docker build -t 86tkstar/react-test-app -f ./frontend/Dockerfile.dev ./frontend

      - name: Run Tests
        run: docker run 86tkstar/react-test-app npm test

      - name: Build and Push Backend Image
        run: |
          docker build -t 86tkstar/docker-fullstack-app:backend-latest ./backend
          docker push 86tkstar/docker-fullstack-app:backend-latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t 86tkstar/docker-fullstack-app:frontend-latest ./frontend
          docker push 86tkstar/docker-fullstack-app:frontend-latest

      - name: Build and Push Nginx Image
        run: |
          docker build -t 86tkstar/docker-fullstack-app:nginx-latest ./nginx
          docker push 86tkstar/docker-fullstack-app:nginx-latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: 'ap-northeast-2'

      - name: Cleanup old application versions
        run: |
          old_versions=$(aws elasticbeanstalk describe-application-versions --application-name docker-fullstack-app-2 --query 'ApplicationVersions[?VersionLabel!=`current-version`].VersionLabel' --output text)
          for version in $old_versions; do
            aws elasticbeanstalk delete-application-version --application-name docker-fullstack-app-2 --version-label $version --delete-source-bundle
          done

      - name: Generate deployment package
        run: zip deploy.zip docker-compose.yml

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-fullstack-app-2
          environment_name: Docker-fullstack-app-2-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-486157951835
          version_label: ${{ github.sha }}
          region: ap-northeast-2
          deployment_package: deploy.zip
          use_existing_version_if_available: true


