name: Deploy Fullstack app to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image for Tests
        run: docker build -t 86tkstar/react-test-app -f ./frontend/Dockerfile.dev .

      - name: Run Tests
        run: docker run 86tkstar/react-test-app npm test


