name: Deploy Fullstack app to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: echo Docker Login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


      - name: Docker Build for Test
        run: docker build -t 86tkstar/react-test-app -f ./frontend/Dockerfile.dev

      - name: Run Test
        run: docker run -e CI=true 86tkstar/react-test-app npm run test
